export const divisions = [
  {
    name: "KSB",
    images: [
      { src: "/images/KSB/Arsalan Padhur Rohman.jpg", name: "Arsalan Padhur Rohman", jabatan: "Ketua Himpunan", instagram: "https://www.instagram.com/arsalan.pdhr" },
      { src: "/images/KSB/ryandika diva fahlevi.jpg", name: "Ryan Diva Fahlevi", jabatan: "Wakil Ketua", instagram: "https://www.instagram.com/ryandika.fhlv" },
      { src: "/images/KSB/sastriani.jpg", name: "Sastriani Prajadepa", jabatan: "Sekretaris 1", instagram: "https://www.instagram.com/sastrianiipr/" },
      { src: "/images/KSB/Bunga.jpg", name: "Bunga Reva", jabatan: "Sekretaris 2", instagram: "https://www.instagram.com/bungarevaa/" },
      { src: "/images/KSB/Yusrina Fitria Cahyani.jpg", name: "Yusrina Fitria Cahyani", jabatan: "Bendahara 1", instagram: "https://www.instagram.com/ysrnftrchyn/" },
      { src: "/images/KSB/Adilla Sahasika Oktora.jpg", name: "Adilla Sahasika Oktora", jabatan: "Bendahara 2", instagram: "https://www.instagram.com/adillasahasikaaa/" },
    ],
  },
  {
    name: "Litbang",
    images: [
      { src: "/images/LITBANG/Alvizahri.webp", name: "Muhamad Rachel Alvizahri", jabatan: "Ketua Departemen", instagram: "https://www.instagram.com/elrfdnt/" },
      { src: "/images/LITBANG/Enjel.jpg", name: "Enjeleliana Situmorang", jabatan: "Sekretaris" },
      { src: "/images/LITBANG/Rahmat.jpg", name: "Rahmat Topik", jabatan: "Ketua Divisi Penelitian" },
      { src: "/images/LITBANG/Irgi.jpg", name: "Irgi Apriana Abas", jabatan: "Anggota",  instagram: "https://www.instagram.com/ghi00_6/" },
      { src: "/images/LITBANG/Arul.jpg", name: "Muhamad Pahrul Rohmatulloh", jabatan: "Anggota", instagram: "https://www.instagram.com/arla_amerta/" },
      { src: "/images/LITBANG/Haris.jpg", name: "Haris Munandar", jabatan: "Anggota", instagram: "https://www.instagram.com/hrismndr8_/" },
      { src: '/images/LITBANG/Lulu Firdaus.JPG', name: 'Lulu Firdaus', jabatan: "Anggota", instagram: "https://www.instagram.com/lulufirdauss_/" },
      { src: "/images/LITBANG/Aidan.jpg", name: "Aidan Maulana", jabatan: "Anggota", instagram: "https://www.instagram.com/aaaiiiiiiddddaaaannnnnnnn_/" },
      { src: "/images/LITBANG/Ghifari.jpg", name: "Ghifari Diaz Fahrezi", jabatan: "Ketua Divisi Pengembangan", instagram:"https://www.instagram.com/ghifaridiazz/" },
      { src: "/images/LITBANG/Fendi.jpg", name: "Fendi", jabatan: "Anggota", instagram: "https://www.instagram.com/fendzz10.18/" },
      { src: "/images/LITBANG/Aldo.jpg", name: "Archilleus Aldo Kurniyanto", jabatan: "Anggota", instagram: "https://www.instagram.com/archilleusaldo.jpg" },
      // { src: '/images/LITBANG/emot.jpg', name: 'Ridho Syaputra', jabatan: "Anggota", instagram: "https://www.instagram.com/rydhsptr_/" },
      // { src: '/images/LITBANG/emot.jpg', name: 'Tegar Fikri Maulana', jabatan: "Anggota", instagram: "https://www.instagram.com/tgrfkrimln/" },
    ],
  },
  {
    name: "PSDM",
    images: [
      { src: "/images/PSDM/Mohammad Rizky.jpg", name: "Mohammad Rizky", jabatan: "Ketua Departemen", instagram: "https://www.instagram.com/bit.heaven/" },
      { src: "/images/PSDM/Dinar Hafidzah Maesyarah.jpg", name: "Dinar Hafidzah Maesyarah", jabatan: "Sekretaris", instagram: "https://www.instagram.com/dinaarhfi/" },
      { src: "/images/PSDM/Asep Hermawan.jpg", name: "Asep Hermawan", jabatan: "Ketua Divisi Kaderisasi", instagram: "https://www.instagram.com/asephermawan5045/" },
      { src: "/images/PSDM/Alpin Antoni.jpg", name: "Alpin Antoni", jabatan: "Anggota", instagram:"https://www.instagram.com/alpinvynnn_/" },
      // { src: "/images/PSDM/emot.jpg", name: "Arya Wira Yoga", jabatan: "Anggota" },
      { src: "/images/PSDM/Bimo Ghafur Prabowo.jpg", name: "Bimo Ghafur Prabowo", jabatan: "Anggota", instagram: "https://www.instagram.com/omib2_11_5/" },
      { src: "/images/PSDM/Agung Prasetyo.jpg", name: "Agung Prasetyo", jabatan: "Ketua Divisi Pengelolaan & Pengembangan",  instagram: "https://www.instagram.com/wincun.com_/" },
      { src: "/images/PSDM/Gilang Pratama.jpg", name: "Gilang Pratama", jabatan: "Anggota", instagram: "https://www.instagram.com/laangp_/" },
      { src: "/images/PSDM/Imanuel Totti Wijaya .jpg", name: "Imanuel Totti Wijaya", jabatan: "Anggota", instagram: "https://www.instagram.com/totti_thegoodboy17/" },
      { src: "/images/PSDM/Nadia Eka Rahmawati.png", name: "Nadia Eka Rahmawati", jabatan: "Anggota",  instagram: "https://www.instagram.com/just_uj4nn/" },
      // { src: "/images/PSDM/emot.jpg", name: "Ahmad Ariel Rafai", jabatan: "Anggota", instagram: "https://www.instagram.com/ahmadaril56/" },
    ],
  },
  {
    name: "Kominfo",
    images: [
      { src: "/images/KOMINFO/Estiriana chantika.png", name: "Estiriana Chantika", jabatan: "Ketua Departemen", instagram: "https://www.instagram.com/str_chantika/" },
      { src: "/images/KOMINFO/Rahma Sefti Hasanah.jpg", name: "Rahma Sefti Hasanah", jabatan: "Sekretaris", instagram: "https://www.instagram.com/rahmaseft/" },
      { src: "/images/KOMINFO/Nilatus sururiyyah.jpg", name: "Nilatus Sururiyyah", jabatan: "Ketua Divisi Desain & Kreatif", instagram: "https://www.instagram.com/tssnilaa/" },
      { src: "/images/KOMINFO/MUHAMMAD DIVALDO .jpg", name: "Muhamad Divaldo", jabatan: "Anggota", instagram: "https://www.instagram.com/m.dvldoo/" },
      { src: "/images/KOMINFO/ANINDITA BUNKAL.jpg", name: "Anindita Bunkal", jabatan: "Anggota", instagram: "https://www.instagram.com/indi.b" },
      { src: "/images/KOMINFO/Iqra Tri Karunia.jpg", name: "Iqra Tri Karunia", jabatan: "Anggota",  instagram: "https://www.instagram.com/iqratr/" },
      { src: "/images/KOMINFO/NABILA RAHMA  FITRIANA.jpg", name: "Nabila Rahma Fitriana", jabatan: "Anggota", instagram: "https://www.instagram.com/nabila_rftrn/" },
      { src: "/images/KOMINFO/Yudha Gani Azis.jpg", name: "Yudha Gani Azis", jabatan: "Anggota" },
      { src: "/images/KOMINFO/Dimas Bayu Wibiastanto.jpg", name: "Dimas Bayu Wibiastanto", jabatan: "Anggota", instagram: "https://www.instagram.com/bayysaje/" },
      { src: "/images/KOMINFO/Fadilah Nauval Almayda.jpg", name: "Fadilah Nauval Almayda", jabatan: "Ketua Divisi Media & Informasi", instagram:"https://www.instagram.com/nnxxvall/" },
      { src: "/images/KOMINFO/Faiq .jpg", name: "Muhamad Faiq Fadhoilurrofiq", jabatan: "Anggota",  instagram: "https://www.instagram.com/faiq.uhuyy/" },
      { src: "/images/KOMINFO/M.DIMAS BAYU PRATAMA_.jpg", name: "Muhamad Dimas Bayu Pratama", jabatan: "Anggota", instagram: "https://www.instagram.com/massbayy88/" },
      { src: "/images/KOMINFO/AURA SALSABILLA PUTRI.jpg", name: "Aura Salsabilla", jabatan: "Anggota", instagram: "https://www.instagram.com/araabillaaaaaaaaa/" },
      { src: "/images/KOMINFO/Nadia Nur Aulia.jpg", name: "Nadia Nur Aulia", jabatan: "Anggota",  instagram: "https://www.instagram.com/yxllnadd/" },
      { src: "/images/KOMINFO/Aldo Saputra.jpg", name: "Aldo Saputra", jabatan: "Anggota", instagram: "https://www.instagram.com/_anomaliennn/" },
    ],
  },
  {
    name: "Keorganisasian",
    images: [
      { src: "/images/KEORGANISASIAN/Rafly Nathan .jpg", name: "Rafly Nathan Tata Hidayat", jabatan: "Ketua Departemen", instagram: "https://www.instagram.com/22nathan/" },
      { src: "/images/KEORGANISASIAN/Tiara Fitriani.jpeg", name: "Tiara Fitriani", jabatan: "Sekretaris", instagram: "https://www.instagram.com/zorraraaa_" },
      { src: "/images/KEORGANISASIAN/GunturRioSaputra.jpg", name: "Guntur Rio Saputra", jabatan: "Ketua Divisi Advokasi", instagram: "https://www.instagram.com/guntur.rss/" },
      { src: "/images/KEORGANISASIAN/Dini restu aulia.jpg", name: "Dini Restu Aulia", jabatan: "Anggota", instagram: "https://www.instagram.com/auliaax31/" },
      // { src: "/images/KEORGANISASIAN/emot.jpg", name: "Roihan Nurkahfi", jabatan: "Anggota" },
      { src: "/images/KEORGANISASIAN/MUHAMMAD FAIZ FIRMANSYAH.jpg", name: "Muhamad Faiz Firmansyah", jabatan: "Anggota",  instagram: "https://www.instagram.com/vaizyco_/" },
      { src: "/images/KEORGANISASIAN/SITI SELI AGUSTINI.jpg", name: "Siti Seli Agustini", jabatan: "Anggota",  instagram: "https://www.instagram.com/stseliagstniii16/" },
      { src: "/images/KEORGANISASIAN/Eka Rahma Prasetyo .jpg", name: "Eka Rahma Prasetyo", jabatan: "Ketua Divisi Evaluasi & Monitoring", instagram: "https://www.instagram.com/ekaaaa.rhm" },
      { src: "/images/KEORGANISASIAN/Cucumu Indah Amumpuni Pitalenti Widodo.jpg", name: "Cucumu Indah Amumpuni Pitalenti Widodo", jabatan: "Anggota", instagram: "https://www.instagram.com/ccminddd/" },
      { src: "/images/KEORGANISASIAN/Islah Abdul Ghoffar_.jpg", name: "Islah Abdul Ghoffar", jabatan: "Anggota", instagram: "https://www.instagram.com/islahabdulghoffarrr/" },
      { src: "/images/KEORGANISASIAN/ALIEFIA NUR QURRATU_AIN.jpg", name: "Aliefia Nur Qurratu'ain", jabatan: "Anggota",  instagram: "https://www.instagram.com/panurr/" },
    ],
  },
];
